name: my_project
description: A new Dart project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sqlite3: any
  path: any

dev_dependencies:
  lints: ^3.0.0

